from constants import *
db = {
  'afganistan':     { 'loc': AS, 'status': min, 'ideo': na },
  'albania':        { 'loc': EU, 'status': min, 'ideo': na },
  'argentina':      { 'loc': SA, 'status': min, 'ideo': na },
  'australia':      { 'loc': OC, 'status': min, 'ideo': de },
  'austria':        { 'loc': EU, 'status': min, 'ideo': na },
  'belgium':        { 'loc': EU, 'status': min, 'ideo': de },
  'bhutan':         { 'loc': AS, 'status': jk, 'ideo': na },
  'bolivia':        { 'loc': SA, 'status': min, 'ideo': na },
  'brazil':         { 'loc': SA, 'status': min, 'ideo': na },
  'british malaya': { 'loc': OC, 'status': min, 'ideo': de },
  'british raj':    { 'loc': AS, 'status': min, 'ideo': na },
  'bulgaria':       { 'loc': EU, 'status': min, 'ideo': na },
  'canada':         { 'loc': NA, 'status': min, 'ideo': de },
  'chile':          { 'loc': SA, 'status': min, 'ideo': de },
  'china':          { 'loc': AS, 'status': min, 'ideo': na },
  'colombia':       { 'loc': SA, 'status': min, 'ideo': de },
  'communist china':{ 'loc': AS, 'status': min, 'ideo': co },
  'costa rica':     { 'loc': CA, 'status': jk, 'ideo': de },
  'cuba':           { 'loc': CA, 'status': jk, 'ideo': de },
  'czechoslovakia': { 'loc': EU, 'status': min, 'ideo': de },
  'denmark':        { 'loc': EU, 'status': min, 'ideo': de },
  'dominican republic':{ 'loc': CA, 'status': jk, 'ideo': na },
  'dutch east indies': { 'loc': OC, 'status': min, 'ideo': de },
  'ecuador':        { 'loc': SA, 'status': min, 'ideo': de },
  'el salvador':    { 'loc': CA, 'status': min, 'ideo': fa },
  'estonia':        { 'loc': EU, 'status': min, 'ideo': na },
  'ethiopia':       { 'loc': AF, 'status': jk, 'ideo': na },
  'finland':        { 'loc': EU, 'status': min, 'ideo': na },
  'france':         { 'loc': EU, 'status': maj, 'ideo': de },
  'germany':        { 'loc': EU, 'status': maj, 'ideo': fa },
  'greece':         { 'loc': EU, 'status': min, 'ideo': na },
  'guangxi clique': { 'loc': AS, 'status': min, 'ideo': na },
  'guatemala':      { 'loc': CA, 'status': min, 'ideo': na },
  'haiti':          { 'loc': CA, 'status': jk, 'ideo': de },
  'honduras':       { 'loc': CA, 'status': min, 'ideo': na },
  'hungary':        { 'loc': EU, 'status': min, 'ideo': na },
  'iran':           { 'loc': ME, 'status': min, 'ideo': na },
  'iraq':           { 'loc': ME, 'status': min, 'ideo': na },
  'ireland':        { 'loc': EU, 'status': min, 'ideo': de },
  'italy':          { 'loc': EU, 'status': maj, 'ideo': fa },
  'japan':          { 'loc': AS, 'status': maj, 'ideo': fa },
  'latvia':         { 'loc': EU, 'status': min, 'ideo': na },
  'liberia':        { 'loc': AF, 'status': jk, 'ideo': de },
  'lithuania':      { 'loc': EU, 'status': min, 'ideo': na },
  'luxembourg':     { 'loc': EU, 'status': jk, 'ideo': de },
  'manchukuo':      { 'loc': AS, 'status': min, 'ideo': fa },
  'mengkukuo':      { 'loc': AS, 'status': jk, 'ideo': fa },
  'mexico':         { 'loc': NA, 'status': min, 'ideo': na },
  'mongolia':       { 'loc': AS, 'status': jk, 'ideo': co },
  'nepal':          { 'loc': AS, 'status': jk, 'ideo': na },
  'netherlands':    { 'loc': EU, 'status': min, 'ideo': de },
  'new zealand':    { 'loc': OC, 'status': min, 'ideo': de },
  'nicaragua':      { 'loc': CA, 'status': min, 'ideo': na },
  'norway':         { 'loc': EU, 'status': min, 'ideo': de },
  'oman':           { 'loc': ME, 'status': jk, 'ideo': na },
  'panama':         { 'loc': CA, 'status': min, 'ideo': de },
  'paraguay':       { 'loc': SA, 'status': min, 'ideo': co },
  'peru':           { 'loc': SA, 'status': min, 'ideo': fa },
  'philippines':    { 'loc': OC, 'status': min, 'ideo': de },
  'poland':         { 'loc': EU, 'status': min, 'ideo': na },
  'portugal':       { 'loc': EU, 'status': min, 'ideo': na },
  'romania':        { 'loc': EU, 'status': min, 'ideo': de },
  'saudi arabia':   { 'loc': ME, 'status': min, 'ideo': na },
  'shanxi':         { 'loc': AS, 'status': min, 'ideo': na },
  'siam':           { 'loc': AS, 'status': min, 'ideo': na },
  'sinkiang':       { 'loc': AS, 'status': min, 'ideo': co },
  'south africa':   { 'loc': AF, 'status': min, 'ideo': de },
  'ussr':           { 'loc': EU, 'status': maj, 'ideo': co },
  'spain':          { 'loc': EU, 'status': min, 'ideo': de },
  'sweden':         { 'loc': EU, 'status': min, 'ideo': de },
  'switzerland':    { 'loc': EU, 'status': min, 'ideo': de },
  'tannu tuva':     { 'loc': AS, 'status': jk, 'ideo': co },
  'tibet':          { 'loc': AS, 'status': min, 'ideo': na },
  'turkey':         { 'loc': ME, 'status': min, 'ideo': na },
  'united kingdom': { 'loc': EU, 'status': maj, 'ideo': de },
  'united states':  { 'loc': NA, 'status': maj, 'ideo': de },
  'uruguay':        { 'loc': SA, 'status': jk, 'ideo': de },
  'venezuela':      { 'loc': SA, 'status': min, 'ideo': fa },
  'xibei san ma':   { 'loc': AS, 'status': min, 'ideo': na },
  'yemen':          { 'loc': ME, 'status': jk, 'ideo': na },
  'yugoslavia':     { 'loc': EU, 'status': min, 'ideo': na },
  'yunnan':         { 'loc': AS, 'status': min, 'ideo': na }
}
